### ISSUE TITLE
Jekyll 4.2.0 breaks this plugin

### ISSUE THREAD

**Issue by brandonb927** [wildlyinaccurate/jekyll-responsive-image#101]
I just upgraded to [Jekyll 4.2.0](https://jekyllrb.com/docs/history/#v4-2-0) (which was released recently) and noticed that I get an error upon attempting to run my project.

Here is the stacktrace:

```
Configuration file: [...]/_config.yml
Configuration file: [...]/_config_dev.yml
            Source: [...]
       Destination: [...]/build_dev
 Incremental build: disabled. Enable with --incremental
      Generating...
Creating output directory [...]/build_dev/assets/media/r
Generating [...]/build_dev/assets/media/r/imagename.jpg
  Liquid Exception: undefined method `filter_cache' for nil:NilClass in [...]/_posts/postname.md
bundler: failed to load command: jekyll ([...]/.rbenv/versions/2.6.3/bin/jekyll)
NoMethodError: undefined method `filter_cache' for nil:NilClass
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/filters.rb:425:in `item_property'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/filters.rb:385:in `block in sort_input'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/filters.rb:385:in `map'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/filters.rb:385:in `sort_input'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/filters.rb:320:in `sort'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
  [...]lib/jekyll-responsive-image/renderer.rb:28:in `render_responsive_image'
  [...]lib/jekyll-responsive-image/tag.rb:16:in `render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
  [...]lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:131:in `render_liquid'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:80:in `render_document'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `each'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `block in render_docs'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `each_value'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `render_docs'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:210:in `render'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  [...]lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
  [...]lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
  [...]lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
  [...]lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
  [...]lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
  [...]lib/ruby/gems/2.6.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
  [...]bin/jekyll:23:in `load'
  [...]bin/jekyll:23:in `<top (required)>'
```

If I have some time I might file a PR as I have some other modifications in a fork I'd like to have considered upstream.

**Comment by Lominean** [comment]
*fights off bot*

**Comment by inavarrorubio** [comment]
Same problem here.

**Comment by wildlyinaccurate** [comment]
Sorry for such a slow reply on this. I'm not sure whether it's a Jekyll or Liquid change, but it's frustrating to have a breaking change regardless! I'll take a look at #103 and see whether I can get a release ready ASAP.

**Comment by wildlyinaccurate** [comment]
Does anyone have a sample site/config that shows this issue? I can't reproduce it.

**Comment by salomvary** [comment]
> Does anyone have a sample site/config that shows this issue? I can't reproduce it.

Yes, see https://github.com/wildlyinaccurate/jekyll-responsive-image/pull/103#discussion_r563534717

**Comment by sebastianhaas** [comment]
Please don't, this is still an issue.Am 13.02.2021 13:13 schrieb "stale[bot]" <notifications@github.com>:
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
