### ISSUE TITLE
What's the best way to remove this plugin if it is breaking my build?

### ISSUE THREAD

**Issue by davidrhoden** [wildlyinaccurate/jekyll-responsive-image#117]
Sorry, I'm kind of new to Jekyll.

I have a site on CloudCannon for a client. The helpful people at CloudCannon said the plugin [jekyll-responsive-image](https://github.com/wildlyinaccurate/jekyll-responsive-image) is breaking my builds, and I need to "change the front matter related to the images" being processed by the plugin. I presume that is all of them, and I just don't see that being feasible. So I'd like to try removing the plugin.

Here's the error it gives:

 ```
             Generating... 
Creating output directory /usr/local/__site/src/assets/resized/200 
Creating output directory /usr/local/__site/src/_site/assets/resized/200 
Generating /usr/local/__site/src/assets/resized/200/IMAGE-NAME.jpg 
Copying resized image to /usr/local/__site/src/_site/assets/resized/200/IMAGE-NAME.jpg 
Creating output directory /usr/local/__site/src/assets/resized/480 
Creating output directory /usr/local/__site/src/_site/assets/resized/480 
Generating /usr/local/__site/src/assets/resized/480/IMAGE-NAME.jpg 
Copying resized image to /usr/local/__site/src/_site/assets/resized/480/IMAGE-NAME.jpg 
Creating output directory /usr/local/__site/src/assets/resized/800 
Creating output directory /usr/local/__site/src/_site/assets/resized/800 

Generating /usr/local/__site/src/assets/resized/800/IMAGE-NAME.jpg 
Copying resized image to /usr/local/__site/src/_site/assets/resized/800/IMAGE-NAME.jpg 

CloudCannon: ⭐️ Starting cloudcannon-jekyll
       CloudCannon: ⚙️ No config file found at cloudcannon.config.(json|yaml|yml)

       CloudCannon: ⚙️ Falling back to site config
       Deprecation: Document#type is now a key in the #data hash.
       Deprecation: Called by ["/usr/local/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/document.rb:377:in `method_missing'"].
       CloudCannon: 📁 Processed data collection with 0 files
       CloudCannon: 📁 Processed posts collection with 78 files
       CloudCannon: 📂 Ignored drafts collection
       CloudCannon: 📁 Processed pages collection with 2 files
       CloudCannon: 📁 Processed about-us collection with 10 files
       CloudCannon: 📁 Processed community-associations collection with 14 files
       CloudCannon: 📁 Processed risk-advisories collection with 2 files
       CloudCannon: 📁 Processed notifications collection with 1 files
       CloudCannon: 💾 Processed categories data set
       CloudCannon: 💾 Processed tags data set

       CloudCannon: 🏁 Generated _cloudcannon/info.json successfully
Generating /usr/local/__site/src/assets/resized/200/homebg.jpg 
Copying resized image to /usr/local/__site/src/_site/assets/resized/200/homebg.jpg 
Generating /usr/local/__site/src/assets/resized/480/homebg.jpg 
Copying resized image to /usr/local/__site/src/_site/assets/resized/480/homebg.jpg 
Generating /usr/local/__site/src/assets/resized/800/homebg.jpg 

Copying resized image to /usr/local/__site/src/_site/assets/resized/800/homebg.jpg 

  Liquid Exception: (<unknown>): mapping values are not allowed in this context at line 3 column 33 in /_layouts/secondary-no-sidebar.html
jekyll 3.8.6 | Error:  (<unknown>): mapping values are not allowed in this context at line 3 column 33
/usr/local/.rbenv/versions/2.7.3/lib/ruby/2.7.0/psych.rb:456:in `parse': (<unknown>): mapping values are not allowed in this context at line 3 column 33 (Psych::SyntaxError)
	from /usr/local/.rbenv/versions/2.7.3/lib/ruby/2.7.0/psych.rb:456:in `parse_stream'
	from /usr/local/.rbenv/versions/2.7.3/lib/ruby/2.7.0/psych.rb:390:in `parse'
	from /usr/local/.rbenv/versions/2.7.3/lib/ruby/2.7.0/psych.rb:277:in `load'
	from /usr/local/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/jekyll-responsive-image-1.6.0/lib/jekyll-responsive-image/block.rb:13:in `render'
```
The images appear in the templates like this:

`{% responsive_image_block %}{% endresponsive_image_block %}`

Can I replace that with something like `{% image_block %}`?

**Comment by davidrhoden** [comment]
Oh line 3 of `/_layouts/secondary-no-sidebar.html`  is the front-matter delineator (`---`). There's no column 33.

Here's that whole file:
```
---
layout: default
---

{% if page.section %}
  {% assign section=page.section %}
{% elsif page.collection %}
  {% assign section=page.collection %}
{% endif %}
{% assign items=site[section] %}

<section id="secondary-page">

  <div class="container">
    <div id="main-content" class="no-sidebar">
      <div class="container column">

        {{ content }}

      </div>
    </div>

    {% if page.skip-blocks != true %}
      {% include child-menu.html items=items %}
    {% endif %}
  </div>

</section>
```
