### ISSUE TITLE
Liquid syntax error: Unknown tag 'responsive_image'

### ISSUE THREAD

**Issue by mvanaltvorst** [wildlyinaccurate/jekyll-responsive-image#90]
This is the line that is causing all the trouble in my post:
`{% responsive_image path: assets/numworks/unofficial.jpg %}`

Output from `jekyll build`:
```
Configuration file: /home/maurits/Documents/blog/_config.yml
            Source: /home/maurits/Documents/blog
       Destination: /home/maurits/Documents/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/document.rb:449: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
       Jekyll Feed: Generating feed for posts
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
  Liquid Exception: Liquid syntax error (line 88): Unknown tag 'responsive_image' in /home/maurits/Documents/blog/_posts/2020-04-16-numworks-calculator.markdown
jekyll 3.8.5 | Error:  Liquid syntax error (line 88): Unknown tag 'responsive_image'
Traceback (most recent call last):
	47: from /home/maurits/.gem/ruby/2.7.0/bin/bundle:23:in `<main>'
	46: from /home/maurits/.gem/ruby/2.7.0/bin/bundle:23:in `load'
	45: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	44: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	43: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	42: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	41: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	40: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	39: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	38: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	37: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	36: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	35: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	34: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	33: from /home/maurits/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	32: from /home/maurits/.gem/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
	31: from /home/maurits/.gem/ruby/2.7.0/bin/jekyll:23:in `load'
	30: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
	29: from /home/maurits/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	28: from /home/maurits/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	27: from /home/maurits/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	26: from /home/maurits/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	25: from /home/maurits/.gem/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	24: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	23: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
	22: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
	21: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
	20: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:71:in `process'
	19: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:191:in `render'
	18: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `render_docs'
	17: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `each_value'
	16: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `block in render_docs'
	15: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `each'
	14: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	13: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:479:in `render_regenerated'
	12: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:62:in `run'
	11: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:79:in `render_document'
	10: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:121:in `render_liquid'
	 9: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	 7: from /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	 6: from /home/maurits/.gem/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'
	 5: from /home/maurits/.gem/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
	 4: from /home/maurits/.gem/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
	 3: from /home/maurits/.gem/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
	 2: from /home/maurits/.gem/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'
	 1: from /home/maurits/.gem/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/document.rb:11:in `block in parse'
/home/maurits/.gem/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (line 88): Unknown tag 'responsive_image' (Liquid::SyntaxError)
```

I'm using the latest version of this plugin
```
✗ bundle info jekyll-responsive-image
  * jekyll-responsive-image (1.5.5)
	Summary: Responsive image management for Jekyll
	Homepage: https://github.com/wildlyinaccurate/jekyll-responsive-image
	Path: /usr/lib/ruby/gems/2.7.0/gems/jekyll-responsive-image-1.5.5
```

Here's a snippet from my _config.yml:
```
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html
```
I'm using the image.js sample template as my _includes/responsive-image.html

What am I doing wrong?

**Comment by wildlyinaccurate** [comment]
Have you tried `bundle exec jekyll build`?
